version: "0.2"
language: en
dictionaries:
  - css
  - html
  - typescript
enableFiletypes:
  - ignore
  - properties
  - xml
files:
  - "**/.*"
  - "**/*.{css,js,json,jsonc,html,md,scss,svelte,svg,yaml,yml,xml}"
useGitignore: true
ignorePaths:
  - pnpm-lock.yaml
words:
  - cooldown
  - CVEs
  - Decap
  - esbuild
  - hostnames
  - jsdoc
  - kyoshino
  - PKCE
  - singleline
  - Sveltia
  - undici
  - workerd
